# Generated by Django 4.1.7 on 2023-03-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('vram', models.IntegerField()),
                ('pines', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('posicion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ghz', models.FloatField()),
                ('nucleos', models.IntegerField()),
                ('hilos', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('posicion', models.IntegerField()),
            ],
        ),
    ]
