# Generated by Django 4.1.7 on 2023-03-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoPc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('posicion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('memoria', models.IntegerField()),
                ('frecuencia', models.IntegerField()),
                ('precio', models.FloatField()),
                ('posicion', models.IntegerField()),
            ],
        ),
    ]
